Add documentation for advanced diagnostics
GoogleCloudPlatform/gce-automated-ad-join pull request #48
Opened 2022-04-28 06:49 UTC by peterschen

This PR adds documentation on how to enable advanced diagnostics (taking a pcapng capture from the VM joining AD) for troubleshooting/debugging purposes.

2022-04-28 07:17 UTC, jpassing approved these changes

2022-04-28 07:50 UTC, idofl commented on ad-joining/README.md
> +The server side log will provide details on server operations like creating/modiying computer accounts. In some cases additional diagnostics are required. By enabling advanced diagnostics, a network
modiying -> modifying

2022-04-28 07:52 UTC, idofl requested changes
LGTM except for one typo

2022-04-28 12:43 UTC, peterschen commented on ad-joining/README.md
> +The server side log will provide details on server operations like creating/modiying computer accounts. In some cases additional diagnostics are required. By enabling advanced diagnostics, a network
Fixed.

2022-04-28 12:44 UTC, merged

2022-05-01 08:35 UTC, idofl reviewed
LGTM